spring:
    mvc:
      problemdetails:
        enabled: true

    mongodb:
      uri: mongodb://root:1V1jNowos_2gru4rbjZIB47HSHSHVf5lBgUmUDiK7-MaPN3F@512ebc5b-fc55-466b-9e8c-f912cf18c6b9.asia-southeast1.firestore.goog:443/db-capsto?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false


server:
    port: 0

eureka:
    instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}